FROM ubuntu:20.04

# Update packages
RUN apt-get update && apt-get upgrade -y

# Install some basic utilities
RUN apt-get install -y curl wget vim git

# Set timezone (opcional)
ENV TZ=America/Sao_Paulo
RUN apt-get install -y tzdata && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
